export const ADD_PROJECT = "ADD_PROJECT"
export const EDIT_PROJECT = "EDIT_PROJECT "
export const DELETE_PROJECT = "DELETE_PROJECT"
export const SAVE_TASK = "SAVE_TASK"
export const EDIT_TASK = "EDIT_TASK "
export const DELETE_TASK = "DELETE_TASK"
